version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps):'
    labels:
      - 'dependencies'
    groups:
      all-non-major:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(ci):'
    labels:
      - 'ci'
    groups:
      all-actions:
        update-types:
          - 'minor'
          - 'patch'
